#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the eSPDI error-code name table from eSPDI_def.h.

Reads every `#define APC_<NAME> <non-positive integer>` (the SDK's error-code
block) and emits switch cases mapping the value back to its define name, so
runtime errors can print `APC_NOT_SUPPORT_RES` instead of a bare `-27`.
Keeping the SDK header as the single source means an SDK upgrade regenerates
the table with no hand edits.

Python 2.7 and 3.x: CMake runs this through PYTHON_EXECUTABLE, which is
python2 on ROS Melodic.

Usage: gen_espdi_error_names.py <eSPDI_def.h> <output.inc>
"""
import io
import re
import sys

DEFINE = re.compile(r"^\s*#define\s+(APC_\w+)\s+(-\d+|0)\s*(?://.*|/\*.*)?$")


def main():
    header, out_path = sys.argv[1], sys.argv[2]
    names = {}  # value -> first define seen (later duplicates are aliases)
    with io.open(header, encoding="utf-8", errors="replace") as f:
        for line in f:
            m = DEFINE.match(line)
            if not m:
                continue
            name, value = m.group(1), int(m.group(2))
            # Value 0 is APC_OK; other 0-valued APC_* constants (pixel-format
            # and data-type enums elsewhere in the header) would otherwise
            # collide with it. Every error code is negative.
            if value == 0 and name != "APC_OK":
                continue
            names.setdefault(value, name)
    if not names:
        sys.exit("no APC error defines found in {0}".format(header))
    with io.open(out_path, "w", encoding="utf-8") as out:
        out.write(u"// Generated by cmake/gen_espdi_error_names.py from "
                  u"eSPDI_def.h - do not edit.\n")
        for value in sorted(names, reverse=True):
            out.write(u'case {0}: return "{1}";\n'.format(value, names[value]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
